/**
 * Generates `src/abis.ts` from compiled Hardhat artifacts so downstream TS packages
 * (gateway, node-daemon, shared) get the ABIs as `const` for full viem typing.
 *
 * Run automatically by `pnpm build` (after `hardhat compile`). Safe to re-run.
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, '..');

const CONTRACTS: Array<{ exportName: string; sol: string; contract: string }> = [
  { exportName: 'quaisTokenAbi', sol: 'QUAISToken.sol', contract: 'QUAISToken' },
  { exportName: 'nodeRegistryAbi', sol: 'NodeRegistry.sol', contract: 'NodeRegistry' },
  { exportName: 'jobEscrowAbi', sol: 'JobEscrow.sol', contract: 'JobEscrow' },
];

function loadAbi(sol: string, contract: string): unknown {
  const path = join(root, 'artifacts', 'contracts', sol, `${contract}.json`);
  const artifact = JSON.parse(readFileSync(path, 'utf8')) as { abi: unknown };
  return artifact.abi;
}

const banner =
  '// AUTO-GENERATED by scripts/export-abis.ts — do not edit by hand.\n' +
  '// Regenerate with `pnpm --filter @querais/contracts build`.\n\n';

const body = CONTRACTS.map(({ exportName, sol, contract }) => {
  const abi = loadAbi(sol, contract);
  return `export const ${exportName} = ${JSON.stringify(abi, null, 2)} as const;`;
}).join('\n\n');

mkdirSync(join(root, 'src'), { recursive: true });
writeFileSync(join(root, 'src', 'abis.ts'), banner + body + '\n', 'utf8');

console.log(`export-abis: wrote src/abis.ts (${CONTRACTS.length} ABIs)`);
